version: '3.4'

services:
  websiteexercisefe:
    image: websiteexercisefe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3104:3104"
    environment:
      NODE_ENV: production
    volumes:
      - ./dist:/app/dist
